services:
  registry-ui:
    image: joxit/docker-registry-ui:main
    container_name: registry-ui
    restart: always
    ports:
    - 25288:80
    environment:
    - SINGLE_REGISTRY=true
    - REGISTRY_TITLE=Docker Registry UI
    - DELETE_IMAGES=true
    - SHOW_CONTENT_DIGEST=true
    - NGINX_PROXY_PASS_URL=http://192.168.10.20:5000
    - SHOW_CATALOG_NB_TAGS=true
    - CATALOG_MIN_BRANCHES=1
    - CATALOG_MAX_BRANCHES=1
    - TAGLIST_PAGE_SIZE=100
    - REGISTRY_SECURED=false
    - CATALOG_ELEMENTS_LIMIT=1000
