services:
  redis-infile:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-infile
    ports:
    - "6379:6379"
    volumes:
    - ./storage/data:/data
    restart: unless-stopped
