services:
  mysql_3307:
    image: mysql:lts # image long term support
    container_name: mysql_3307
    ports:
    - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysettingpassword
      MYSQL_DATABASE: TemplateDB
    volumes:
    - mysql_3307_data:/var/lib/mysql
    restart: always

  mysql_3308:
    image: mysql:lts # image long term support
    container_name: mysql_3308
    ports:
    - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysettingpassword
      MYSQL_DATABASE: TemplateDB
    volumes:
    - mysql_3308_data:/var/lib/mysql
    restart: always

volumes:
  mysql_3307_data:
  mysql_3308_data:
