services:
  itsower-docker-registry:
    image: registry:2
    container_name: itsower-docker-registry
    ports:
    - "5000:5000"
    restart: always
    volumes:
    - ./storage/itsower-docker-registry/data:/var/lib/registry # 儲存映像的本地目錄
    - ./storage/itsower-docker-registry/auth:/auth # 身份驗證資料夾（可選）
    - ./storage/itsower-docker-registry/certs:/certs # 憑證資料夾（可選）
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      # 可選的身份驗證
      # REGISTRY_AUTH: htpasswd
      # REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      # REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      # 可選的 HTTPS 支持
      # REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      # REGISTRY_HTTP_TLS_KEY: /certs/domain.key
